POST https://bettle-backend.herokuapp.com/users/login
Content-Type: application/json

{
    "name":"Wasseypur",
    "password":"Wasseypur"
}

###

GET http://localhost:3000/main
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiV2Fzc2V5cHVyIiwiaWF0IjoxNjI0MzUyNjIyLCJleHAiOjE2MjQzNTMyMjJ9.GddqHJ2xCt1XPuNev-DJFlnypU-04Kf4v9Ab-lxg_dc"
}

###

DELETE http://localhost:3000/users/main
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFkbGFwdXIiLCJpYXQiOjE2MjQxMzcxNjYsImV4cCI6MTYyNDEzNzE3Nn0.vBB9VQ92UC3PUqLcdV-kOZVx7Qu0Yu9wJQ7iTJArU3M"
}

###

GET http://localhost:3000/main


###

PUT http://localhost:3000/customer
Content-Type: application/json

{
    "pincode":"700018",
    "contact":"1829128901"
}
