POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name":"Wassesdasdypur",
    "password":"Wasseypur"
}

###

POST http://localhost:3000/users/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFkbGFwdXIiLCJpYXQiOjE2MjQxMzcxNjYsImV4cCI6MTYyNDEzNzE3Nn0.vBB9VQ92UC3PUqLcdV-kOZVx7Qu0Yu9wJQ7iTJArU3M"
}

###

DELETE http://localhost:3000/users/logout
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFkbGFwdXIiLCJpYXQiOjE2MjQxMzcxNjYsImV4cCI6MTYyNDEzNzE3Nn0.vBB9VQ92UC3PUqLcdV-kOZVx7Qu0Yu9wJQ7iTJArU3M"
}

###

GET http://localhost:3000/main

Authorization: B eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFkbGFwdXIiLCJpYXQiOjE2MjQxMzU2MDMsImV4cCI6MTYyNDEzNTYxM30.UyvEYD5AWJRBC157ni2AkU0ULG9QDVusTuMl-e5hKRI


###

PUT http://localhost:3000/customer
Content-Type: application/json

{
    "pincode":"700018",
    "contact":"1829128901"
}
