GET http://localhost:3000/users/login
Content-Type: application/json

{
    "name":"Badlapur",
    "password":"Badlapur"
}

###

GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQmFkbGFwdXIiLCJpYXQiOjE2MjQxMTE4NjEsImV4cCI6MTYyNDExMTg2Mn0.X750-S8CAYxLab6UcGy-vj7hPIieMVDkxPRKcaUNq9A